Add scale bar to map
theopensystemslab/map pull request #60
Opened 2021-09-21 11:18 UTC by melzreal

### Description of change

Add scale bar to maps
![image](https://user-images.githubusercontent.com/9452321/134161262-3ffd849b-cfcb-4b6c-bbab-8158180927e5.png)

### Story Link

https://trello.com/c/3LkxI6Kd/448-map-scale-bar-required-on-decision-notice

Co-authored-by: Rhian Lewis <rhianatwork@gmail.com>

2021-09-21 12:53 UTC, jessicamcinchak requested changes
very exciting & useful first feature contribution :tada:

left a couple comments, happy to talk through if anything is unclear!

2021-09-21 12:53 UTC, jessicamcinchak commented on src/my-map.ts
> +      }).extend([scaleControl()]),
this scale bar is a super handy visual feature for map orientation! my only suggestion is that we don't make it visible by default all the time, but rather add a [Lit property](https://lit.dev/docs/components/properties/) so that end users can opt in or out of showing it for various use cases/implementations.

one way to do that could be like this: 
1. in `my-map.ts` around L114, add:
```ts
@property({ type: Boolean })
showScale = false;
```
configurable properties are just a long unordered list with most recent additions at the bottom currently, open to organization ideas here! current rule of thumb is that boolean properties are always false by default, see [here](https://github.com/theopensystemslab/map/issues/37) for context

2. then this line could use a conditional ternary operator to _only_ add the scale when the property is true:  
```ts
...}).extend(this.showScale ? [scaleControl()] : []),
```

3. finally, in our individual implementations of this component, we would specify that we want to show the scale bar in our html element like this:
```html
<my-map zoom="18" drawMode showScale />
```
omitting the `showScale` property would simply hide it

2021-09-21 12:53 UTC, jessicamcinchak commented on src/scale-line.ts
> +  control = new ScaleLine({
this could just be `return new ScaleLine({` and & then you wouldn't have to declare `control` globally above on line 4 :)

2021-09-21 15:58 UTC, melzreal commented on src/my-map.ts
> +      }).extend([scaleControl()]),
thanks this is super thorough! Sounds good to me - I've put the question to the partners since the ticket we had seems to suggest they always need a scale bar for legal purposes, so it seemed logical to just enforce it everywhere - but actually it is probably best that the base map just has that option as you suggest and then we turn it on everywhere we need it - just double checking what they want

2021-09-21 16:53 UTC, jessicamcinchak commented on src/my-map.ts
> +      }).extend([scaleControl()]),
awesome, glad this worked out! on our side, toggling it on/off will be super helpful as we're often trying to keep the public-facing applicant maps as least cluttered & technical as possible. 

will approve this now & once you merge it I'll add it to the next release I have queued up [here](https://github.com/theopensystemslab/map/pull/59) -- which we can plan to merge/publish first thing tmrw morning :slightly_smiling_face: :rocket:

2021-09-21 16:53 UTC, jessicamcinchak approved these changes

2021-09-22 08:46 UTC, melzreal commented on src/my-map.ts
> +      }).extend([scaleControl()]),
thanks for the approval! It occurred to me today though that instead of hard coding the bar type they decided on, we could instead pass it on as an argument since Os does provide two different bar types - just in case they change their mind and then want the other one..

2021-09-22 08:47 UTC, melzreal commented on src/my-map.ts
> +      }).extend([scaleControl()]),
(will figure out how to do it and incorporate) - also should I update documentation somewhere? Was wondering how would anyone apart from us know that showScale can be turned on and off

2021-09-22 08:59 UTC, jessicamcinchak commented on src/my-map.ts
> +      }).extend([scaleControl()]),
cool! the bar style seems like a nice argument to have available for more custom implementation options. of course feel to keep working even though i approved, just re-request when you're done i guess?

as for documentation, i've been adding examples direct to the README for now! there's also [this issue](https://github.com/theopensystemslab/map/issues/26) to figure out a longer term solution, maybe Storybook or something similar. we're still pre-v1, so can stay lightweight & flexible about this for now in my opinion until we settle on a solution we like :slightly_smiling_face:

2021-09-22 09:31 UTC, jessicamcinchak commented on src/scale-line.ts
> +  }
i think this if/else can be simplified to: 
```ts
export function scaleControl(showBar: boolean) {
  return new ScaleLine({
    units: 'metric',
    bar: showBar,
    steps: 4,
    text: true,
    minWidth: 140,
  });
}
```

small detail: typescript is lowercase boolean, while Lit property type is uppercase B ! Linter will complain about that.

2021-09-22 09:32 UTC, jessicamcinchak commented on src/my-map.ts
> +  showBar = false;
:+1: another property makes sense to me here! I do find this naming slightly confusing though, wonder if `useBarStyleScale` is more descriptive for the second one here? up to you though!

2021-09-22 10:10 UTC, merged