wip: `<postcode-search />` & `<address-autocomplete />` components
theopensystemslab/map pull request #93
Opened 2021-12-02 21:21 UTC by jessicamcinchak

sandbox for new web components to do address lookups!

1. `<postcode-search />` is a GOV.UK-styled input that validates UK postcodes using these [postcode utility methods](https://www.npmjs.com/package/postcode). i added [govuk-frontend](https://frontend.design-system.service.gov.uk/installing-with-npm/) & sass for styling; [this example repo](https://github.com/e111077/vite-lit-element-ts-sass) was handy for configuring sass with lit & vite.
![Screenshot from 2021-12-02 22-18-43](https://user-images.githubusercontent.com/5132349/144504728-81fab63d-5ee8-4066-842d-8305b02a879c.png)![Screenshot from 2021-12-02 22-18-29](https://user-images.githubusercontent.com/5132349/144504741-e809ef0c-464f-4b97-a442-c53044237b97.png)

2. [todo] `<address-autocomplete />` fetches addresses in a given UK postcode (or polygon?!) using the [OS Places API](https://apidocs.os.uk/docs/os-places-overview) and displays them using GOV.UK's [accessible-autocomplete](https://github.com/alphagov/accessible-autocomplete) component

todo: 
- research/decide on file structure if this repo is becoming a library of components rather than single one
- global sass file or per component? would be nice to take advantage of per-component govuk style imports if possible
- figure out best build config & `/dist` exports (want to include multiple entry files in vite's `build.lib.entry`??)
- maybe finally think of better names for stuff

2022-03-21 12:31 UTC, DafyddLlyr requested changes
Looking great! A few very minor comments on the postcode component, but no show stoppers 👍 

The unique id issue is something that shows up in a few places - we can ignore this for now if this is more pragmatic, but just put a card on the backlog to refactor when we hit pages?

2022-03-21 12:31 UTC, DafyddLlyr commented on src/components/address-autocomplete/index.ts
> +          </div>`
This is nice!

2022-03-21 12:31 UTC, DafyddLlyr commented on index.html
> +        -->
👍

2022-03-21 12:31 UTC, DafyddLlyr commented on index.html
> +      <div stye="margin-bottom:1em">
```suggestion
      <div style="margin-bottom:1em">
```

2022-03-21 13:03 UTC, jessicamcinchak commented on src/components/postcode-search/index.ts
> +          .value=${this._postcode}
ah so this dot is actually an intentional, significant Lit detail! Lit uses `.value` to assign the value property, whereas `value` would assign the attribute. I'll add a comment saying so, it definitely looks a bit unusual.

I found these links helpful for wrapping my head around some of these syntax quirks:
- https://levelup.gitconnected.com/build-a-material-like-input-web-component-using-litelement-20e9e0d203b6
- https://stackoverflow.com/questions/61430631/onchange-not-fired-in-input-field-of-litelement

2022-03-22 08:43 UTC, jessicamcinchak commented on src/components/postcode-search/index.ts
> +        </span>
good catch - updated! additionally added `role="status"` to the autocomplete container to be safe, as we'll still plan to conditionally render that component.

2022-03-22 08:44 UTC, jessicamcinchak commented on src/components/postcode-search/index.ts
> +          id="event-name-error"
good point - `id` & `errorId` are now user-configurable properties - so we can handle these custom cases & pages in the future!

2022-03-22 08:44 UTC, jessicamcinchak commented on src/components/postcode-search/index.ts
> +      });
updated! much nicer visually :+1:

2022-03-22 09:26 UTC, jessicamcinchak commented on vite.config.ts
> +      name: "ComponentLib",
to doublecheck: I won't break any existing imports or the cdn script (eg https://cdn.jsdelivr.net/npm/@opensystemslab/map@0.4.0) by changing `build.lib.name`, right? imports are only reliant on the component names in `index.ts` which haven't changed?

still want to revisit naming at some point, but not intending to break existing map imports here for us or BOPs.

2022-03-22 09:26 UTC, DafyddLlyr commented on src/components/postcode-search/index.ts
> +          .value=${this._postcode}
Good to know, and thanks for the links! 👍 

Looking forward to getting a bit more hands on with Lit and getting to grips with some of this.

2022-03-22 09:34 UTC, jessicamcinchak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Switch to GOV UK accessible-autocomplete component to fix final audit issues](https://trello.com/c/xy0PoaJT/1839-switch-to-gov-uk-accessible-autocomplete-component-to-fix-final-audit-issues)

2022-03-22 09:41 UTC, DafyddLlyr approved these changes

2022-03-22 09:41 UTC, DafyddLlyr commented on src/components/postcode-search/index.ts
> +    //   <input /> uses Lit ".value" syntax to set property, whereas "value" would set attribute
👍

2022-03-22 09:41 UTC, DafyddLlyr commented on vite.config.ts
> +      name: "ComponentLib",
Yeah from what I can tell this shouldn't break any external calls to the library. The name of the entire package in NPM will be consistent, as will the name used in `index.ts` which is what's used in PlanX, BOPS etc.

We can always give BOPS a heads up and ask them to pin their version of the package until we test if we want to be super cautious. I think we can test this very quickly/easily once deployed though right?

2022-03-22 10:33 UTC, merged